engines:
  rubocop:
    enabled: false
  golint:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - server/**
  - "**.js"
exclude_paths:
- Test/**/*
- seed/**/*
- client/**/*
