version: '2'

services:
  database:
       image: mongo
       restart: always
       ports:
         - "27017"
       networks:
         rlcnet:
           ipv4_address: 172.10.1.3
       command: "--smallfiles --logpath=/dev/null"

  nodeapp:
       build: .
       restart: always
       ports:
          - "3001"
       networks:
         rlcnet:
           ipv4_address: 172.10.1.2
       environment:
         PORT: 3001
         DB_HOST: 172.10.1.3

  dataloader:
       image: mongo
       networks:
          - rlcnet
       volumes:
          - ${PWD}:/data
       command: "mongorestore --host 172.10.1.3 --port 27017 --db devops_new --drop /data/seed/mongodump/devops_new/"

  webfront:
       image: nginx
       ports:
          - "80:80"
       volumes:
          - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf
       restart: always
       networks:
         rlcnet:
           ipv4_address: 172.10.1.1

networks:
  rlcnet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.10.0.0/16
         gateway: 172.10.5.254